### ISSUE TITLE
cloudwatch log group not created

### ISSUE THREAD

**Issue by tgam-smickeler** [jnonino/terraform-aws-ecs-fargate-task-definition#1]
I created a task using this module but it fails to run due to `/ecs/service/${var.name_preffix}` not being created, so the task errors out with

```
Status reason	CannotStartContainerError: Error response from daemon: failed to initialize logging driver: failed to create Cloudwatch log stream: ResourceNotFoundException: The specified log group does not exist. status code: 400, request id: 7463029c-9f12-4e3f-b914-f
```

**Comment by jnonino** [comment]
Hello, please try with this new version [1.0.2](https://registry.terraform.io/modules/jnonino/ecs-fargate-task-definition/aws/1.0.2)

**Comment by tgam-smickeler** [comment]
> Hello, please try with this new version [1.0.2](https://registry.terraform.io/modules/jnonino/ecs-fargate-task-definition/aws/1.0.2)

Looks to be working.

Thanks again for the quick fix.
